source 'https://rubygems.org'

gem 'sinatra'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'dotenv'
gem 'haml'
gem 'sinatra-flash'

group :development, :test do
  gem 'rspec'
  gem 'pry'
  gem 'dm-sweatshop'
  gem 'ffaker'
  gem 'blue-shell'
  gem 'rack-test'
end
