source 'https://rubygems.org'

gem 'sinatra'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'dotenv'
gem 'haml'

# dev
gem 'rspec'
gem 'pry'
gem 'dm-sweatshop'
gem 'ffaker'
gem 'blue-shell'
gem 'rack-test'
